services:
  api:
    image: 1developer1/datingapp-service
    container_name: datingapp_api
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
        - db
    environment:
         - ASPNETCORE_ENVIRONMENT=Development
         - ConnectionStrings__DefaultConnection=Server=db;Initial Catalog=datting_app;TrustServerCertificate=True;Integrated Security=False;User ID= sa;Password=0>?Xc+r6v5;
         - ASPNETCORE_Kestrel__Certificates__Default__Password=2184782Andrey
         - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    ports:
      - "6000:80"
      - "6001:443" 
    volumes:
      - ~/.aspnet/https:/https:ro

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: datingapp_db
    environment:
        - SA_PASSWORD=0>?Xc+r6v5
        - ACCEPT_EULA=Y
    ports:
        - "1433:1433"

        