apiVersion: v1
kind: Service
metadata:
  name: datingservice-srv
spec:
  type: NodePort
  selector:
    app: datingservice
  ports:
    - name: datingservice
      protocol: TCP
      port: 443
      targetPort: 443